name: Smoke Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  check:
    name: Smoke Test (${{ matrix.os }}.${{ matrix.node }})
    strategy:
      fail-fast: false
      matrix:
        node: ['18.20.0', '20', '22']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: 🧑‍🔧 Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@dda4788290998366da86b6a4f497909644397bb2 # v4.0.2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: webdriverio
          path: .
          filename: webdriverio-build.zip

      - name: Smoke Tests
        run: pnpm run test:smoke
        shell: bash

      - name: Check Git Context
        if: matrix.os != 'windows-latest'
        uses: ./.github/workflows/actions/check-git-context
